name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: fusion-engineering/setup-git-credentials@v2.0.6
        with:
          credentials: ${{ secrets.ACTIONS_GIT_CREDENTIALS }}
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}